import Link from 'next/link';
import { projectStarters } from '@/features/project-planning/project-starters';

const capabilities = [
  { id: '01', name: 'Project Brain', purpose: 'Inspect saved requirements, assumptions, provenance and immutable revisions.', status: 'AVAILABLE' },
  { id: '02', name: 'Versions', purpose: 'Inspect successful simulation versions and historical sample previews.', status: 'SIMULATION' },
  { id: '03', name: 'Deployments', purpose: 'Inspect internal fixture records. External deployment is planned.', status: 'SIMULATION' },
  { id: '04', name: 'Runtime / Logs', purpose: 'No generated app is running. Real health and terminal logs are planned.', status: 'PLANNED' },
  { id: '05', name: 'Natural-language changes', purpose: 'Save context-bound requests and optionally demonstrate an update. No source is changed.', status: 'RECORDED INTENT' },
];

export function PlatformIndex() {
  return <div className="platform-index">
    <section id="platform" className="platform-register" aria-labelledby="platform-title"><div className="register-heading"><span className="meta">SYSTEM INDEX / CURRENT FOUNDATION</span><h2 id="platform-title">A workspace.<br />For the life of your software.</h2><p>Real draft planning and persisted projects are available. Workspace execution remains explicitly Simulation.</p><Link href="/projects" className="register-workspace-link">Open workspace <span aria-hidden="true">↗</span></Link></div><div className="capability-ledger">{capabilities.map(item => <div key={item.id}><span className="meta">{item.id}</span><div><h3>{item.name}</h3><p>{item.purpose}</p></div><span className="planned-label">{item.status}</span></div>)}</div></section>
    <section id="templates" className="template-register" aria-labelledby="template-title"><div className="index-section-heading"><span className="meta">01 / TEMPLATES</span><h2 id="template-title">A starting point, not a blank page.</h2><p>Starter briefs are available now. A full application-template library is planned.</p></div><div className="template-list">{projectStarters.map(item => <Link href={`/projects/new?starter=${item.id}`} key={item.id}><span className={`template-symbol starter-${item.id}`} aria-hidden="true">{item.id === 'crm' ? '▥' : item.id === 'booking' ? '▤' : '⌘'}</span><span><small>{item.number} / {item.category}</small><strong>{item.title}</strong></span><span className="template-action">Use brief ↗</span></Link>)}</div></section>
    <section id="connections" className="connection-register" aria-labelledby="connections-title"><div className="index-section-heading"><span className="meta">02 / CONNECTIONS — PLANNED</span><h2 id="connections-title">Software doesn’t work alone.</h2><p>A future connector ecosystem for project context, product services and the tools your team uses. No connections can be authorized here yet.</p></div><dl><div><dt>Development</dt><dd><span>GitHub / GitLab</span><span>CI / Sentry</span><small>Source context & verification</small></dd></div><div><dt>Product services</dt><dd><span>Payments / Database</span><span>Email / Storage / Analytics</span><small>Application capabilities</small></dd></div><div><dt>Business tools</dt><dd><span>Calendar / Slack / Notion</span><span>Gmail / CRM / Sheets</span><small>Workflows & business context</small></dd></div></dl></section>
    <section id="docs" className="docs-register" aria-labelledby="docs-title"><div className="index-section-heading"><span className="meta">03 / DOCS</span><h2 id="docs-title">Before your first command.</h2><p>A short guide to planning and the saved workspace.</p></div><div className="planning-docs"><details open><summary>What happens when I submit a brief?</summary><p>The homepage composer returns a real structured draft plan: title, summary, target users, features, recommended stack and milestones. Save a project from the Projects workspace to persist its original brief and deterministic Brain scaffold. These are separate actions; neither generates an application.</p></details><details><summary>What should I put in the composer?</summary><p>Describe who the product serves, the problem or outcome, and the essentials. For example: “Reduce missed appointments at my studio with booking, reminders and a daily schedule.”</p></details><details><summary>What is remembered today?</summary><p>The homepage draft disappears on reload. Saved projects retain their original brief, Brain revisions, requests, Simulation events and versions. Open Projects to return to them. The homepage sample is an illustration; saved workspace Trace reads persisted simulation events.</p><Link className="text-action" href="/projects">Open saved projects ↗</Link></details></div></section>
  </div>;
}
