import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {setTimeout as delay} from 'node:timers/promises';
import {launchTestBrowser,stopBrowserServer} from './browser-process.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
async function until(check){for(let i=0;i<150;i++){if(await check().catch(()=>false))return;await delay(100);}throw Error('Expected authenticated state not reached');}
test('provider-method integration, account ownership, expiry and browser recovery with controlled RSA OIDC',{timeout:240000},async()=>{
 const api=process.env.M5_API_URL,port=process.env.P2A_WEB_PORT,gateway=process.env.AUTH_GATEWAY_TOKEN;assert.ok(api&&port&&gateway);
 const base=`http://127.0.0.1:${port}`,directory=root+'/test-results/authentication';await mkdir(directory,{recursive:true});
 const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',port],{cwd:root,env:{...process.env,APP_ENV:'test',AUTH_MODE:'oidc',AUTH_GATEWAY_TOKEN:gateway,API_INTERNAL_URL:api,NEXT_PUBLIC_APP_URL:base},stdio:'ignore'});let browser;const measurements=[];
 async function control(kind){const response=await fetch(api+'/test/auth-state',{method:'POST',headers:{Authorization:`Bearer ${gateway}`,'Content-Type':'application/json'},body:JSON.stringify({kind})});assert.equal(response.status,200);}
 try{
 await until(async()=> (await fetch(base)).ok);browser=await launchTestBrowser({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));const axe=process.env.M5_AXE_SCRIPT?await readFile(process.env.M5_AXE_SCRIPT,'utf8'):null;
 async function capture(state){for(const theme of process.env.F01_EDITORIAL_AUDIT==='1'?['light','dark']:[null]){if(theme)await page.getByRole('combobox',{name:'Color theme',exact:true}).selectOption(theme);for(const width of [1440,375,768,720]){await page.setViewportSize({width,height:width===720?500:1000});await page.evaluate(async()=>{await document.fonts.ready;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${state} overflow ${width}`);if(axe){await page.addScriptTag({content:axe});assert.deepEqual(await page.evaluate(async()=> (await axe.run(document,{iframes:false,runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa']}})).violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))),[],`${state} accessibility ${width}`);}if(width===1440||width===375)await page.screenshot({path:`${directory}/${theme?theme+'-':''}${state}-${width}.png`,fullPage:true});measurements.push({theme,state,width,overflow:false,accessibility:axe?'passed':'not_run'});}await page.setViewportSize({width:1440,height:1000});}if(process.env.F01_EDITORIAL_AUDIT==='1')await page.getByRole('combobox',{name:'Color theme',exact:true}).selectOption('light');}
 await page.goto(base+'/sign-up?returnTo=%2Faccount');await page.getByRole('heading',{name:'Create your account'}).waitFor();await capture('signup-methods');
 const google=page.getByRole('button',{name:'Continue with Google'});await google.focus();await page.keyboard.press('Enter');await page.waitForURL(/\/oidc\/authorize/);assert.equal(new URL(page.url()).searchParams.get('connection'),'google-oauth2');assert.equal(new URL(page.url()).searchParams.get('screen_hint'),'signup');assert.equal(new URL(page.url()).searchParams.get('prompt'),'login');await page.getByRole('button',{name:'Sign in as test owner A'}).click();await page.waitForURL(base+'/account');await page.getByRole('textbox',{name:'Display name'}).waitFor();await page.getByText('✓ Verified',{exact:true}).waitFor();await capture('account-verified');
 const before=await page.evaluate(async()=> (await (await fetch('/api/v1/session')).json()).principal.id);await page.getByRole('textbox',{name:'Display name'}).fill('Mira Factory');const save=page.getByRole('button',{name:'Save profile'});let writes=0;await page.route('**/api/v1/account',async route=>{if(route.request().method()==='PATCH')writes++;await route.continue();});await save.evaluate(button=>{button.click();button.click();});await page.getByText('Your profile is saved.').waitFor();assert.equal(writes,1);await page.getByRole('link',{name:/Mira Factory · Authenticated owner/}).waitFor();await page.reload();await until(async()=>await page.getByRole('textbox',{name:'Display name'}).inputValue()==='Mira Factory');await capture('profile-reloaded');
 await control('expire');await page.reload();await page.getByRole('link',{name:'Sign in again'}).waitFor();await capture('session-expired');await page.getByRole('link',{name:'Sign in again'}).click();await page.getByRole('button',{name:'Continue with Email'}).click();await page.waitForURL(/\/oidc\/authorize/);assert.equal(new URL(page.url()).searchParams.get('connection'),'email');await page.getByRole('button',{name:'Sign in as test owner A'}).click();await page.waitForURL(base+'/account');await page.getByRole('textbox',{name:'Display name'}).waitFor();assert.equal(await page.evaluate(async()=> (await (await fetch('/api/v1/session')).json()).principal.id),before);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL(/signed_out=1/);assert.equal(await page.evaluate(async()=> (await fetch('/api/v1/session')).status),401);await capture('signed-out');
 await control('unverified');await page.getByRole('button',{name:'Continue with Email'}).click();await page.getByRole('button',{name:'Sign in as test owner B'}).click();await page.waitForURL(/error=verification/);assert.equal(await page.evaluate(async()=> (await fetch('/api/v1/session')).status),401);await capture('verification-required');await control('verified');
 await page.getByRole('button',{name:'Continue with Email'}).click();await page.getByRole('button',{name:'Sign in as test owner B'}).click();await page.waitForURL(base+'/projects');await page.goto(base+'/account');await until(async()=>await page.getByRole('textbox',{name:'Display name'}).inputValue()!=='Mira Factory');assert.notEqual(await page.evaluate(async()=> (await (await fetch('/api/v1/session')).json()).principal.id),before);await capture('separate-owner');
 await page.goto(base+'/api/auth/callback?state=invalid&code=already-used');await page.waitForURL(/error=expired/);await capture('expired-link');await page.goto(base+'/api/auth/callback?error=access_denied&error_description=private-provider-debug');await page.waitForURL(/error=canceled/);assert.equal(await page.getByText('private-provider-debug').count(),0);await capture('canceled-login');
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base+'/sign-in');assert.equal(await page.locator('.button').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');await page.getByRole('button',{name:'Continue with Google'}).focus();assert.equal(await page.evaluate(()=>document.activeElement?.textContent.includes('Continue with Google')),true);
 assert.deepEqual(errors,[]);await writeFile(directory+'/result.json',JSON.stringify({status:'passed',provider:'controlled RSA OIDC fixture',google_live:'not_run',magic_link_delivery:'not_run',measurements},null,2));
 }catch(error){if(browser){const page=browser.contexts().flatMap(context=>context.pages()).at(-1);await page?.screenshot({path:directory+'/failure.png',fullPage:true});}throw error;}finally{await browser?.close();await stopBrowserServer(server);}
});
