// Browser rendering and command UI acceptance from persisted-contract fixtures.
// Real Docker/provider acceptance remains a separate mandatory check.
import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {setTimeout as delay} from 'node:timers/promises';
import {launchTestBrowser,stopBrowserServer} from './browser-process.mjs';
import * as f from './build-observation-fixtures.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
async function until(check){for(let i=0;i<160;i++){if(await check().catch(()=>false))return;await delay(100);}throw Error('Build state did not reach its observed UI');}
test('observed build screen and persistent project journey',{timeout:180000},async()=>{
 const probe=createServer();await new Promise((resolve,reject)=>{probe.once('error',reject);probe.listen(0,'127.0.0.1',resolve);});const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));
 const base=`http://127.0.0.1:${port}`,path=`/projects/${f.ids.project}`,directory=root+'/test-results/build-journey';
 const env={...process.env,APP_ENV:'test',AUTH_MODE:'development',EXECUTION_MODE:'real',DEV_API_TOKEN:'synthetic-rendering-token-12345678901234567890',API_INTERNAL_URL:'http://127.0.0.1:9',NEXT_PUBLIC_APP_URL:base};delete env.OPENAI_API_KEY;delete env.F01_VERCEL_TOKEN;
 const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],{cwd:root,env,stdio:'ignore'});
 let browser;const commands=[],errors=[],captures=[];let d=null,v=null,live=null,revision=1,clock=Date.now(),heartbeat=true,readUnavailable=false,executionMode='real';
  const shift=value=>typeof value==='string'&&Number.isFinite(Date.parse(value))&&Date.parse(value)>=f.now-200000&&Date.parse(value)<=f.now+4000000?new Date(Date.parse(value)+clock-f.now).toISOString():Array.isArray(value)?value.map(shift):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([key,item])=>[key,shift(item)])):value;
  const savedStep=()=>{d.progress_updated_at=new Date().toISOString();revision++;};
 function state(){const s=shift(f.snapshot({latest_run:d?.run??null,active_run:d&&['queued','running'].includes(d.run.status)?d.run:null,current_version:v,recent_events:[],last_sequence:revision}));s.project.current_version_id=s.current_version?.id??null;s.project.lifecycle=s.active_run?s.active_run.status==='queued'?'understanding':'building':s.current_version?'live':s.latest_run?.status==='failed'?'error':'idle';if(d?.run.status==='running'&&heartbeat)s.active_run.last_heartbeat_at=new Date(Date.now()).toISOString();return s;}
 try{
  await until(async()=> (await fetch(base)).ok);browser=await launchTestBrowser({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await mkdir(directory,{recursive:true});
  await page.route('**/api/v1/**',async route=>{
   const url=new URL(route.request().url()),resource=url.pathname.replace('/api/v1','');let body;
   if(resource==='/session')body={principal:{id:f.ids.brain,display_name:'Contract test owner',identity_mode:'development'},capabilities:{execution_mode:executionMode,real_generation:executionMode==='real',source_artifacts:executionMode==='real',external_deployment:executionMode==='real',simulation_runner:executionMode==='simulated'}};
   else if(resource.endsWith('/workspace'))body=state();
   else if(resource.endsWith('/builds')&&route.request().method()==='POST'){commands.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});d=f.detail({run:f.run(),phase:'context_resolution'});revision++;body=shift(d.run);}
   else if(resource.endsWith('/builds')){body=shift({items:d?.run.mode==='real'?[d]:[]});if(body.items.length&&d?.run.status==='running'&&heartbeat)body.items[0].run.last_heartbeat_at=new Date(Date.now()).toISOString();}
   else if(resource.endsWith('/retry')){commands.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});d=f.detail({run:f.run({id:crypto.randomUUID(),retry_of_run_id:d.run.id,attempt:2,created_at:new Date().toISOString()}),phase:'context_resolution'});savedStep();body=d.run;}
   else if(resource.endsWith('/cancel')){commands.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});d.cancel_requested=true;savedStep();body=shift(d.run);}
   else if(/\/builds\/[0-9a-f-]{36}$/.test(resource)){if(readUnavailable)return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'SERVICE_UNAVAILABLE',message:'Synthetic interrupted read'}})});body=shift(d);if(d?.run.status==='running'&&heartbeat)body.run.last_heartbeat_at=new Date(Date.now()).toISOString();}
   else if(resource.endsWith('/planning/proposals'))body={items:!v?[f.proposal({reviewed:true})]:[]};
   else if(resource.endsWith('/releases'))body=shift(f.releases({current_release_id:live?.id??null,releases:live?[live]:[]}));
   else if(resource.endsWith('/events/stream'))return route.abort('failed');
   else if(resource.endsWith('/events'))body={items:[],next_cursor:null};
   else body={items:[],next_cursor:null};
   await route.fulfill({status:resource.endsWith('/builds')&&route.request().method()==='POST'?202:200,contentType:'application/json',body:JSON.stringify(body)});
  });
  await page.route('http://localhost:3031/p/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="en"><title>Contract preview fixture</title><main><h1>Verified rendering fixture</h1></main></html>'}));
  async function capture(name){for(const theme of process.env.F01_EDITORIAL_AUDIT==='1'?['light','dark']:[null]){if(theme)await page.getByRole('combobox',{name:'Color theme',exact:true}).selectOption(theme);assert.equal(await page.locator('.global-rail .rail-nav a[aria-current]').evaluate(el=>getComputedStyle(el).transitionProperty.split(',').some(p=>['color','background','background-color','all'].includes(p.trim()))),false,'Theme changes must not interpolate navigation text and background independently.');for(const width of [1440,1140,375,720]){await page.setViewportSize({width,height:width===720?500:1000});await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${name} ${width} overflow`);assert.equal(await page.locator('.journey-v3').evaluate(el=>el.querySelector('ol').getBoundingClientRect().width>=el.getBoundingClientRect().width*.85),true,`${name} ${width} journey fills its panel`);assert.ok(await page.locator('.workspace-preview .button-primary:visible:not(:disabled)').count()<=1,`${name} one primary action`);if(process.env.M5_AXE_SCRIPT){await page.addScriptTag({content:await readFile(process.env.M5_AXE_SCRIPT,'utf8')});const violations=await page.evaluate(async()=> (await axe.run(document,{iframes:false,runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa']}})).violations);if(violations.length){await writeFile(`${directory}/${theme?theme+'-':''}${name}-${width}-axe.json`,JSON.stringify(violations,null,2));await page.screenshot({path:`${directory}/${theme?theme+'-':''}${name}-${width}-failed.png`,fullPage:true});}assert.deepEqual(violations.map(v=>v.id),[],`${name} ${width} accessibility`);}await page.screenshot({path:`${directory}/${theme?theme+'-':''}${name}-${width}.png`,fullPage:true});captures.push({name,theme,width});}await page.setViewportSize({width:1440,height:1000});}if(process.env.F01_EDITORIAL_AUDIT==='1')await page.getByRole('combobox',{name:'Color theme',exact:true}).selectOption('light');}
  await page.goto(base+path+'?step=build');await page.getByRole('button',{name:'Build reviewed plan'}).waitFor();assert.equal(await page.getByRole('button',{name:'Build reviewed plan'}).evaluate(el=>getComputedStyle(el).transitionProperty.split(',').some(p=>['color','background','background-color','all'].includes(p.trim()))),false,'Button state changes must preserve contrast without interpolated foreground/background colors.');await page.getByRole('button',{name:'Build reviewed plan'}).evaluate(button=>{button.click();button.click();});await page.getByRole('heading',{name:'Build queued',exact:true}).waitFor();assert.equal(commands.length,1);assert.equal(await page.getByRole('heading',{name:'Preview pending.',exact:true}).count(),0);await capture('queued');
  d=f.detail();revision++;await until(()=>page.locator('.build-timeline li[aria-current=step] h4').getByText('Generating code',{exact:true}).isVisible());await capture('generation-pending');await page.reload();await page.getByRole('heading',{name:'Building your application',exact:true}).waitFor();assert.equal(commands.length,1);await capture('generating-reload');
  readUnavailable=true;revision++;await page.getByRole('heading',{name:'Build needs a status check'}).waitFor();assert.equal(await page.locator('.build-activity').getAttribute('data-animated'),'false');await capture('interrupted-read');readUnavailable=false;d.progress_updated_at=new Date().toISOString();await page.getByRole('button',{name:'Check saved build status'}).click();await page.getByRole('heading',{name:'Building your application',exact:true}).waitFor();assert.equal(commands.length,1);
  d=f.detail({phase:'install',candidates:[f.candidate()],current_candidate_evidence:f.checks().slice(0,2)});savedStep();await until(()=>page.locator('.build-timeline li[aria-current=step] h4').getByText('Building',{exact:true}).isVisible());await capture('building');
  d.phase='build';d.current_candidate_evidence=f.checks().slice(0,4);savedStep();await until(()=>page.locator('.build-timeline li[aria-current=step] h4').getByText('Verifying',{exact:true}).isVisible());await capture('verifying');
  d.phase='generation_pending';d.repair_attempts=1;d.current_candidate_evidence=[f.evidence('typecheck',1)];savedStep();await page.getByRole('heading',{name:'Repairing your application'}).waitFor();assert.equal(await page.locator('.build-timeline li').nth(2).getAttribute('data-state'),'pending');await capture('repairing');
  heartbeat=false;d.run.last_heartbeat_at=f.stamp(-90000);d.run.started_at=f.stamp(-95000);d.progress_updated_at=f.stamp(-90000);revision++;await page.getByRole('heading',{name:'Build needs a status check'}).waitFor();assert.equal(await page.locator('.build-activity').getAttribute('data-animated'),'false');await capture('worker-stall');await page.getByRole('button',{name:'Check saved build status'}).click();assert.equal(commands.length,1,'Read-only status checks cannot duplicate a build.');
  d.run={...d.run,status:'failed',error_code:'REPAIR_EXHAUSTED'};revision++;await page.reload();await page.getByRole('heading',{name:'Build needs attention',exact:true}).waitFor();await capture('failed');
  d.run.error_code='SOURCE_PROPOSAL_REJECTED';savedStep();await page.reload();await page.getByText(/The proposed source failed the required source-integrity checks/).waitFor();await capture('rejected-source');
  const failedRun=d.run.id;await page.getByRole('button',{name:'Retry real build'}).evaluate(button=>{button.click();button.click();});await page.getByRole('heading',{name:'Build queued',exact:true}).waitFor();assert.equal(commands.length,2);assert.equal(d.run.retry_of_run_id,failedRun);assert.deepEqual(JSON.parse(commands.at(-1).body),{});await capture('retry-queued');
  d=f.detail({run:f.run({id:crypto.randomUUID(),status:'canceled',error_code:'BUILD_CANCELED'})});revision++;await page.reload();await page.getByRole('heading',{name:'Build canceled',exact:true}).waitFor();await capture('canceled');
  heartbeat=true;d=f.detail({run:f.run({id:crypto.randomUUID(),status:'running',started_at:new Date().toISOString(),last_heartbeat_at:new Date().toISOString()}),phase:'test',candidates:[f.candidate()],current_candidate_evidence:f.checks().slice(0,5),progress_updated_at:new Date().toISOString()});revision++;await page.reload();await until(()=>page.locator('.build-timeline li[aria-current=step] h4').getByText('Preparing preview',{exact:true}).isVisible());await capture('preparing-preview');
  d={...d,run:{...d.run,status:'succeeded'},phase:'preview_ready',current_candidate_evidence:f.checks()};v=f.version({run_id:d.run.id});revision++;await page.getByRole('link',{name:'Continue to publish'}).waitFor();await page.frameLocator('iframe[title="Verified generated application preview"]').getByRole('heading',{name:'Verified rendering fixture'}).waitFor();assert.equal(new URL(page.url()).searchParams.has('step'),false);assert.equal(await page.locator('.build-pane').getAttribute('open'),null);await capture('succeeded-auto-preview');
  live=f.release();d=f.detail({run:f.run({id:crypto.randomUUID(),status:'running',base_version_id:v.id,started_at:new Date().toISOString(),last_heartbeat_at:new Date().toISOString()}),phase:'generation_pending',progress_updated_at:new Date().toISOString()});revision++;await page.reload();await page.getByText('Last confirmed live release',{exact:true}).waitFor();assert.match(await page.getByRole('region',{name:'Current project step'}).innerText(),/Update journey/);assert.equal(await page.locator('.preserved-preview').getAttribute('open'),null);await capture('update-live-preserved');
  await page.getByRole('button',{name:'Cancel real build'}).click();await page.getByRole('heading',{name:'Cancellation requested',exact:true}).waitFor();assert.equal(await page.locator('.build-activity').getAttribute('data-animated'),'false');await capture('cancellation-requested');d.run={...d.run,status:'canceled',error_code:'BUILD_CANCELED',finished_at:new Date().toISOString()};savedStep();await page.getByRole('heading',{name:'Build canceled',exact:true}).waitFor();assert.equal(v.id,f.ids.version);assert.equal(live.id,f.ids.release);await capture('update-canceled');
  await page.emulateMedia({reducedMotion:'reduce'});await page.reload();assert.equal(await page.locator('.factory-activity b').evaluate(el=>getComputedStyle(el).animationName),'none');
  executionMode='simulated';live=v=null;d=f.detail({run:f.run({id:crypto.randomUUID(),mode:'simulated',status:'running',started_at:new Date().toISOString(),scenario_id:'crm-v1'})});savedStep();await page.reload();await page.getByRole('heading',{name:'Demonstration in progress',exact:true}).waitFor();assert.equal(await page.getByRole('region',{name:'Real build',exact:true}).count(),0);assert.equal(await page.locator('.build-activity').count(),0);await capture('demonstration-keeps-provenance');assert.deepEqual(errors,[]);
  await writeFile(directory+'/result.json',JSON.stringify({browser:'passed',data:'generated-contract fixtures',docker:'not_run',provider:'not_run',captures},null,2));
 }catch(error){console.error('Captured browser errors:',errors);throw error;}finally{await browser?.close();await stopBrowserServer(server);}
});
