import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {setTimeout as delay} from 'node:timers/promises';
import {chromium} from 'playwright';
import {productVisualAudit} from './product-visual-audit.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
async function until(check){for(let i=0;i<300;i++){if(await check().catch(()=>false))return;await delay(100);}throw Error('Expected commercial journey state not reached');}
test('signed-in commercial journey with accepted Docker and controlled deployment provider',{timeout:480000},async t=>{
 const api=process.env.M5_API_URL,port=process.env.P2A_WEB_PORT,gateway=process.env.AUTH_GATEWAY_TOKEN;
 assert.ok(api&&port&&gateway,'Run the disposable commercial browser harness.');
 const base=`http://127.0.0.1:${port}`,env={...process.env,APP_ENV:'test',AUTH_MODE:'oidc',EXECUTION_MODE:'real',AUTH_GATEWAY_TOKEN:gateway,API_INTERNAL_URL:api,NEXT_PUBLIC_APP_URL:base};
 delete env.OPENAI_API_KEY;delete env.F01_VERCEL_TOKEN;
 const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',port],{cwd:root,env,stdio:'ignore'});
 const evidence=`${root}/test-results/commercial`;await mkdir(evidence,{recursive:true});let browser;
 async function step(kind){const response=await fetch(`${api}/test/commercial-step`,{method:'POST',headers:{Authorization:`Bearer ${gateway}`,'Content-Type':'application/json'},body:JSON.stringify({kind})});assert.equal(response.status,200);return response.json();}
 async function read(page,path){return page.evaluate(async path=>{const response=await fetch(`/api/v1${path}`);return {status:response.status,data:await response.json()};},path);}
 try{
  await until(async()=> (await fetch(base)).ok);browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const visual=await productVisualAudit(page,root+'/test-results/ux-system-v2');
  await page.goto(base);await page.getByRole('heading',{level:1}).waitFor();await visual.capture('start');
  await page.goto(`${base}/sign-in`);await visual.capture('sign-in');await page.getByRole('button',{name:'Sign in securely'}).click();await page.getByRole('button',{name:'Sign in as test owner A'}).click();await page.waitForURL(`${base}/projects`);await page.getByRole('heading',{name:/Start with a brief/}).waitFor();await visual.capture('projects-empty');
  await page.goto(`${base}/projects/new`);await visual.capture('create');await page.getByRole('textbox',{name:/Project title/}).fill('Commercial acceptance');await page.getByRole('textbox',{name:'Product brief'}).fill('Build a browser-only leads dashboard for a property agency.');await page.getByRole('button',{name:'Create project',exact:true}).click();await page.waitForURL(/\/projects\/[0-9a-f-]{36}$/);
  const id=new URL(page.url()).pathname.split('/').at(-1),releasePanel=page.getByRole('region',{name:'Production release'});await page.getByRole('heading',{name:'Preview pending.'}).waitFor();await visual.capture('workspace-empty');
  await page.goto(`${base}/projects/${id}/planning`);await page.getByRole('button',{name:'Plan from original brief'}).waitFor();await visual.capture('planning-empty');await page.getByRole('button',{name:'Plan from original brief'}).click();await page.getByRole('heading',{name:'Commercial dashboard plan',exact:true}).waitFor();await visual.capture('plan-review');await page.getByRole('button',{name:'Approve this plan'}).click();await page.getByRole('link',{name:'Continue to build'}).waitFor();await visual.capture('plan-approved');await page.getByRole('link',{name:'Continue to build'}).click();await page.getByRole('button',{name:'Build reviewed plan'}).waitFor();await visual.capture('build-reviewed');await page.getByRole('button',{name:'Build reviewed plan'}).click();await until(async()=>Boolean((await read(page,`/projects/${id}/workspace`)).data.active_run));await page.getByRole('heading',{name:'Build queued',exact:true}).waitFor();await visual.capture('build-queued');await step('build');await page.reload();
  await page.frameLocator('iframe[title="Verified generated application preview"]').getByRole('main').filter({hasText:'Verified dashboard'}).waitFor({timeout:30000});
  await visual.capture('preview-verified');const first=(await read(page,`/projects/${id}/workspace`)).data;assert.equal(await page.getByRole('link',{name:'Review a plan',exact:true}).count(),0);
  await page.getByRole('link',{name:'Review preview',exact:true}).click();await page.locator('.publish-pane > summary').click();await releasePanel.getByRole('button',{name:'Set up production hosting'}).click();await until(async()=>Boolean((await read(page,`/projects/${id}/releases`)).data.hosting_setup));await step('target');await page.reload();await releasePanel.getByRole('button',{name:'Prepare production package'}).click();await until(async()=>Boolean((await read(page,`/projects/${id}/releases`)).data.preparations.find(p=>p.state==='queued')));await step('package');await page.reload();
  const deploy=releasePanel.getByRole('button',{name:'Deploy reviewed version'});await deploy.waitFor();assert.equal(await deploy.isDisabled(),true);await releasePanel.getByRole('checkbox').check();
  let lose=true;const commands=[];
  await page.route('**/api/v1/projects/*/releases',async route=>{if(route.request().method()!=='POST')return route.continue();commands.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});if(lose){lose=false;await route.fetch();await route.abort('failed');}else await route.continue();});
  await visual.capture('deploy-review');await deploy.click();await until(()=>releasePanel.getByRole('button',{name:'Resolve saved release command'}).isEnabled());await page.reload();await releasePanel.getByRole('button',{name:'Resolve saved release command'}).click();await until(async()=>!(await releasePanel.getByRole('button',{name:'Resolve saved release command'}).isVisible()));assert.equal(commands.length,2);assert.deepEqual(commands[0],commands[1]);await step('release');await page.reload();await releasePanel.getByRole('heading',{name:'Your product is live'}).waitFor();
  await visual.capture('live');const liveOne=(await read(page,`/projects/${id}/releases`)).data;assert.equal(liveOne.releases.length,1);assert.ok(liveOne.current_release_id);assert.equal(await releasePanel.getByRole('link',{name:'Open public URL ↗'}).getAttribute('target'),'_blank');
  // Modify through the existing pinned-source request/planning pipeline.
  await page.goto(`${base}/projects/${id}/planning`);await page.getByRole('textbox',{name:'Describe the change'}).fill('Add a priority filter to the existing leads dashboard.');await page.getByRole('button',{name:'Plan this change'}).click();await page.getByRole('heading',{name:'Priority change proposal',exact:true}).waitFor();await page.getByRole('button',{name:'Approve this plan'}).first().click();await page.getByRole('link',{name:'Continue to build'}).first().click();await page.getByRole('heading',{name:'Ready for the next build',exact:true}).waitFor();await visual.capture('rebuild-reviewed');await page.getByRole('button',{name:'Build reviewed plan'}).click();await until(async()=>Boolean((await read(page,`/projects/${id}/workspace`)).data.active_run));await step('build');await page.reload();
  const second=(await read(page,`/projects/${id}/workspace`)).data;assert.notEqual(second.current_version.id,first.current_version.id);assert.equal((await read(page,`/projects/${id}/releases`)).data.current_release_id,liveOne.current_release_id);
  const filter=page.frameLocator('iframe[title="Verified generated application preview"]').getByLabel('Priority filter');await filter.waitFor();await until(async()=>await page.getByText('Loading your application preview…',{exact:true}).count()===0);await filter.selectOption('high');await until(async()=>await page.frameLocator('iframe[title="Verified generated application preview"]').getByText('Orchard',{exact:true}).count()===0);
  await page.getByRole('link',{name:'Review preview',exact:true}).click();await page.locator('.publish-pane > summary').click();await releasePanel.getByText(/Preview version 2 is ahead of production/).waitFor();await visual.capture('preview-update');await releasePanel.getByRole('button',{name:'Prepare production package'}).click();await until(async()=>Boolean((await read(page,`/projects/${id}/releases`)).data.preparations.find(p=>p.state==='queued')));await step('package');await page.reload();await releasePanel.getByRole('checkbox').check();await releasePanel.getByRole('button',{name:'Redeploy reviewed version'}).click();await until(async()=>(await read(page,`/projects/${id}/releases`)).data.releases.length===2);const stats=await step('release');await page.reload();await releasePanel.getByRole('heading',{name:'Your product is live'}).waitFor();
  const liveTwo=(await read(page,`/projects/${id}/releases`)).data;assert.notEqual(liveTwo.current_release_id,liveOne.current_release_id);assert.equal(liveTwo.target_generation,2);assert.equal(stats.stage_calls,2);assert.equal(stats.promote_calls,2);
  await page.goto(`${base}/projects/${id}/versions`);await page.getByText('Release history',{exact:true}).waitFor();await page.getByRole('heading',{name:'Version 2',exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:/no production deployment/}).count(),0);await visual.capture('versions');assert.equal((await read(page,`/projects/${id}/versions`)).data.items.length,2);await page.goto(`${base}/projects/${id}?version=${first.current_version.id}`);await page.frameLocator('iframe[title="Verified generated application preview"]').getByRole('main').filter({hasText:'Verified dashboard'}).waitFor();assert.equal(await page.getByRole('button',{name:'Deploy reviewed version'}).count(),0);
  await visual.capture('historical-preview');
  for(const width of [375,768,1280,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${width}px overflow`);if(process.env.M5_AXE_SCRIPT){await page.addScriptTag({content:await readFile(process.env.M5_AXE_SCRIPT,'utf8')});assert.deepEqual(await page.evaluate(async()=> (await axe.run(document,{iframes:false,runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa']}})).violations.map(v=>v.id)),[],`${width}px accessibility`);}await page.screenshot({path:`${evidence}/history-${width}.png`,fullPage:true});}
  if(process.env.F01_VISUAL_AUDIT==='1'){
   for(const [route,title] of [['brief','Original brief'],['brain','Project Brain'],['activity','Activity'],['settings','Project settings']]){await page.goto(`${base}/projects/${id}/${route}`);await page.getByRole('heading',{name:title,exact:true}).waitFor();await until(()=>page.getByText('Loading saved records…',{exact:true}).count().then(n=>n===0));await visual.capture(route);}
   await page.goto(`${base}/projects`);await page.getByRole('link',{name:/Commercial acceptance/}).waitFor();await page.getByRole('region',{name:'Saved projects'}).getByText('Version ready',{exact:true}).waitFor();await page.locator('.dashboard-filters > summary').click();assert.equal(await page.locator('#project-search').evaluate(el=>getComputedStyle(el).cursor),'text');assert.equal(await page.locator('#project-filter').evaluate(el=>getComputedStyle(el).cursor),'pointer');await visual.capture('projects');
   await page.goto(`${base}/account`);await page.getByRole('heading',{level:1}).waitFor();await visual.capture('account');
   await page.goto(`${base}/projects/${id}?panel=trace`);await page.getByRole('region',{name:'Build Trace',exact:true}).waitFor();await visual.capture('build-trace');await page.getByRole('button',{name:'Close inspector'}).click();
   await page.emulateMedia({reducedMotion:'reduce'});await visual.capture('reduced-motion');assert.equal(await page.locator('.button').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');
   await page.route('**/api/v1/projects?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'SERVICE_UNAVAILABLE'}})}));await page.goto(`${base}/projects`);await page.getByRole('button',{name:'Retry project list'}).waitFor();await visual.capture('projects-error');await page.unroute('**/api/v1/projects?*');await page.getByRole('button',{name:'Retry project list'}).click();await page.getByRole('link',{name:/Commercial acceptance/}).waitFor();
   let releaseRead;const hold=new Promise(resolve=>{releaseRead=resolve;});await page.route('**/api/v1/projects?*',async route=>{await hold;await route.continue();});await page.goto(`${base}/projects`);await page.locator('.project-skeletons').waitFor();await visual.capture('projects-loading',{scan:false});releaseRead();await page.unroute('**/api/v1/projects?*');await page.getByRole('link',{name:/Commercial acceptance/}).waitFor();
   await visual.finish();
  }
  assert.deepEqual(errors,[]);await writeFile(`${evidence}/result.json`,JSON.stringify({browser_journey:'passed',docker:'real accepted image',oidc:'synthetic RSA',model:'controlled',deployment_provider:'controlled',live_provider:'not_run',project_id:id,versions:[first.current_version.id,second.current_version.id],releases:[liveOne.current_release_id,liveTwo.current_release_id]},null,2));
 }catch(error){if(browser){const page=browser.contexts().flatMap(c=>c.pages()).at(-1);if(page)await page.screenshot({path:`${evidence}/failure.png`,fullPage:true});}throw error;}
 finally{await browser?.close();server.kill('SIGTERM');await new Promise(resolve=>{if(server.exitCode!==null)resolve();else server.once('exit',resolve);});}
});
