// Actual PostgreSQL/worker/Docker states. Source transport and identity are controlled.
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {setTimeout as delay} from 'node:timers/promises';
import {launchTestBrowser,stopBrowserServer} from './browser-process.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
async function until(check){for(let i=0;i<900;i++){if(await check().catch(()=>false))return;await delay(100);}throw Error('Expected persisted real build state did not appear');}
test('actual worker build, repair, cancel, quiet generation and process-loss recovery',{timeout:480000},async()=>{
 const api=process.env.M5_API_URL,gateway=process.env.AUTH_GATEWAY_TOKEN,port=process.env.P2A_WEB_PORT,base=`http://127.0.0.1:${port}`;
 assert.ok(api&&gateway&&port,'Use scripts/test-m5.py --build-states.');
 const env={...process.env,APP_ENV:'test',AUTH_MODE:'oidc',AUTH_GATEWAY_TOKEN:gateway,API_INTERNAL_URL:api,NEXT_PUBLIC_APP_URL:base};delete env.OPENAI_API_KEY;delete env.F01_VERCEL_TOKEN;
 const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',port],{cwd:root,env,stdio:'ignore'});
 let browser,worker,page,projectId;const captures=[],errors=[],directory=root+'/test-results/real-build-states';await mkdir(directory,{recursive:true});
 async function step(kind){const r=await fetch(api+'/test/commercial-step',{method:'POST',headers:{Authorization:`Bearer ${gateway}`,'Content-Type':'application/json'},body:JSON.stringify({kind})});assert.equal(r.status,200);return r.json();}
 try{
  await until(async()=> (await fetch(base)).ok);browser=await launchTestBrowser({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
  async function saved(id){return page.evaluate(async id=>(await fetch(`/api/v1/projects/${id}/workspace`,{cache:'no-store'})).json(),id);}
  async function capture(name){console.info('Observed real state: '+name);for(const width of [1440,375]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.M5_AXE_SCRIPT){await page.addScriptTag({content:await readFile(process.env.M5_AXE_SCRIPT,'utf8')});assert.deepEqual(await page.evaluate(async()=>(await axe.run(document,{iframes:false,runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa']}})).violations.map(v=>v.id)),[]);}await page.screenshot({path:`${directory}/${name}-${width}.png`,fullPage:true});captures.push({name,width});}await page.setViewportSize({width:1440,height:1000});}
  async function stage(label){await page.locator('.build-timeline li[aria-current=step][data-state=active] h4').getByText(label,{exact:true}).waitFor({timeout:90000});}
  await page.goto(base+'/sign-in');await page.getByRole('button',{name:'Sign in securely'}).click();await page.getByRole('button',{name:'Sign in as test owner A'}).click();await page.waitForURL(base+'/projects');await page.getByRole('link',{name:'New project'}).click();await page.locator('.creation-title-details > summary').click();await page.getByRole('textbox',{name:/Project title/}).fill('Observed real worker');await page.getByRole('textbox',{name:'Product brief'}).fill('Build a browser-only leads dashboard. No backend or external APIs.');await page.getByRole('button',{name:'Create project',exact:true}).click();await page.waitForURL(/\/projects\/[0-9a-f-]{36}$/);const id=new URL(page.url()).pathname.split('/').at(-1);projectId=id;
  await page.goto(base+`/projects/${id}/planning`);await page.getByRole('button',{name:'Plan from original brief'}).click();await page.getByRole('button',{name:'Approve this plan'}).click();await page.getByRole('link',{name:'Continue to build'}).click();await page.getByRole('button',{name:'Build reviewed plan'}).click();await page.getByRole('heading',{name:'Build queued',exact:true}).waitFor();await capture('queued');
  worker=step('build');await stage('Generating code');await capture('generating');await page.reload();await stage('Generating code');await capture('generation-reload');await stage('Building');await capture('building');await stage('Verifying');await capture('verifying');await stage('Preparing preview');await capture('preparing-preview');await worker;worker=null;
  await page.getByRole('link',{name:'Continue to publish'}).waitFor();const good=await saved(id);assert.equal(good.current_version.mode,'real');await capture('succeeded');
  await page.goto(base+`/projects/${id}/planning`);await page.getByRole('textbox',{name:'Describe the change'}).fill('Add a priority filter to the existing dashboard while preserving the last good version.');await page.getByRole('button',{name:'Plan this change'}).click();await page.getByRole('button',{name:'Approve this plan'}).first().click();await page.getByRole('link',{name:'Continue to build'}).first().click();await step('fail-build');await page.getByRole('button',{name:'Build reviewed plan'}).click();await page.getByRole('heading',{name:'Build queued',exact:true}).waitFor();worker=step('build');await page.getByRole('heading',{name:'Repairing your application'}).waitFor({timeout:120000});await capture('repairing');await worker;worker=null;await page.getByRole('heading',{name:'Build needs attention',exact:true}).waitFor();await capture('failed');assert.equal((await saved(id)).current_version.id,good.current_version.id);assert.equal((await saved(id)).latest_run.error_code,'REPAIR_EXHAUSTED');
  await step('reset-failures');const failed=(await saved(id)).latest_run.id;await page.getByRole('button',{name:'Retry real build'}).click();await page.getByRole('heading',{name:'Build queued',exact:true}).waitFor();assert.equal((await saved(id)).latest_run.retry_of_run_id,failed);await page.getByRole('button',{name:'Cancel real build'}).click();await page.getByRole('heading',{name:'Build canceled',exact:true}).waitFor();await capture('canceled');assert.equal((await saved(id)).current_version.id,good.current_version.id);
  await page.getByRole('button',{name:'Build reviewed plan'}).click();await page.getByRole('heading',{name:'Build queued',exact:true}).waitFor();await step('start-held-worker');await stage('Generating code');await page.getByRole('heading',{name:'Waiting for a saved result'}).waitFor({timeout:70000});assert.equal(await page.locator('.build-activity').getAttribute('data-animated'),'false');await capture('quiet-generation');await step('kill-held-worker');await page.getByRole('heading',{name:'Build needs a status check'}).waitFor({timeout:70000});assert.equal((await saved(id)).active_run.status,'running');assert.equal(await page.locator('.build-activity').getAttribute('data-animated'),'false');await page.reload();await page.getByRole('heading',{name:'Build needs a status check'}).waitFor();await capture('worker-stall-reload');
  const recovered=await step('build');await page.getByRole('heading',{name:'Build needs attention',exact:true}).waitFor();const after=await saved(id);assert.equal(after.latest_run.error_code,'PROVIDER_OUTCOME_UNKNOWN');assert.equal(after.current_version.id,good.current_version.id);await capture('recovered-without-replay');assert.deepEqual(errors,[]);
  await writeFile(directory+'/result.json',JSON.stringify({browser:'passed',postgres:'real disposable',docker:'real accepted image',worker_process_loss:'actually terminated owned worker',model:'controlled',public_provider:'not_run',source_calls:recovered.source_calls,captures},null,2));
 }catch(error){if(page){await page.screenshot({path:directory+'/failure.png',fullPage:true});if(projectId)await writeFile(directory+'/failure-state.json',JSON.stringify(await page.evaluate(async id=>({workspace:await (await fetch(`/api/v1/projects/${id}/workspace`)).json(),builds:await (await fetch(`/api/v1/projects/${id}/builds`)).json()}),projectId),null,2));}throw error;}
 finally{await step('kill-held-worker').catch(()=>{});await worker?.catch(()=>{});await browser?.close();await stopBrowserServer(server);}
});
