import test from 'node:test';import assert from 'node:assert/strict';
import {handleBuild} from '../src/lib/workspace/build-server.ts';
import {eventRecord} from '../src/lib/workspace/trace.ts';
const id='ab56889d-a04c-41bb-831e-429948d34cb8',token='synthetic-m4-token-12345678901234567890';
const env={APP_ENV:'test',DEV_API_TOKEN:token,API_INTERNAL_URL:'http://127.0.0.1:8000',NEXT_PUBLIC_APP_URL:'http://127.0.0.1:3000'};
function request(body,origin='http://127.0.0.1:3000'){return new Request(`http://127.0.0.1:3000/api/v1/projects/${id}/builds`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':'build-once',Authorization:'Bearer forged'},body:JSON.stringify(body)});}
test('real build gateway uses generated client and private identity',async()=>{const result=await handleBuild(request({proposal_id:id}),id,[],env,async req=>{assert.equal(req.url,`http://127.0.0.1:8000/v1/projects/${id}/builds`);assert.equal(req.headers.get('authorization'),`Bearer ${token}`);assert.equal(req.headers.get('idempotency-key'),'build-once');assert.deepEqual(await req.json(),{proposal_id:id});return Response.json({id},{status:202,headers:{'Set-Cookie':'secret=1'}});});assert.equal(result.status,202);assert.equal(result.headers.get('set-cookie'),null);});
test('real build gateway rejects model commands and foreign origins',async()=>{let calls=0;const send=async()=>{calls++;return Response.json({});};assert.equal((await handleBuild(request({proposal_id:id,command:'rm -rf /'}),id,[],env,send)).status,422);assert.equal((await handleBuild(request({proposal_id:id},'https://evil.test'),id,[],env,send)).status,403);assert.equal(calls,0);});
test('uncertain real build retains exact idempotency key across replay',async()=>{const keys=[];for(let n=0;n<2;n++)await handleBuild(request({proposal_id:id}),id,[],env,async req=>{keys.push(req.headers.get('idempotency-key'));throw Error('offline');});assert.deepEqual(keys,['build-once','build-once']);});
test('trace accepts real provenance and preserves simulation labels',()=>{const base={id,project_id:id,sequence:1,type:'execution.build',message:'Build observed.',mode:'real',phase:'verifying',severity:'info',payload:{schema_version:1,execution_phase:'build'}};assert.equal(eventRecord(base,id),true);assert.equal(eventRecord({...base,mode:'simulated'},id),true);assert.equal(eventRecord({...base,mode:'invented'},id),false);});
