'use client';
import Link from 'next/link';
import {useState} from 'react';
import {PulseMark} from '@/features/project-pulse/project-pulse';
import {authDestination} from '@/lib/auth/navigation';
export function AuthScreen({signup=false,options,error,signedOut,returnTo}:{signup?:boolean;options:{oidc:boolean;google:boolean;email:boolean;available:boolean};error?:string;signedOut?:boolean;returnTo?:string}){
 const [pending,setPending]=useState('');
 const messages:Record<string,string>={unavailable:'We couldn’t complete sign-in. Your projects are safe. Try again when the connection returns.',canceled:'Sign-in was canceled. You can try again when you’re ready.',expired:'This sign-in link expired or was already used. Request a new link in the same browser.',verification:'Please verify your email with the identity provider, then sign in again.',limited:'Too many sign-in attempts. Wait a moment before trying again.',method:'This sign-in method hasn’t been configured yet. Use another available method.'};
 function choice(method:string,label:string,primary=false){return <form method="post" action="/api/auth/sign-in" onSubmit={event=>{if(pending){event.preventDefault();return;}setPending(method);}}><input type="hidden" name="method" value={method}/><input type="hidden" name="intent" value={signup?'sign-up':'sign-in'}/><input type="hidden" name="returnTo" value={authDestination(returnTo)}/><button type="submit" className={`button ${primary?'button-primary':'button-secondary'} auth-choice`} disabled={Boolean(pending)}>{method==='google'&&<span aria-hidden="true" className="google-symbol">G</span>}{pending===method?'Connecting securely…':label}<span aria-hidden="true">↗</span></button></form>;}
 return <main className="auth-page"><Link href="/" className="os-wordmark" aria-label="F01 home"><PulseMark/><span>F01<small>SOFTWARE FACTORY</small></span></Link><div className="auth-layout"><aside className="auth-story"><span className="meta">AN IDEA IS ONLY THE BEGINNING</span><h2>Make it real.<br/><em>Make it yours.</em></h2><p>A place for your ideas to become useful software—and keep getting better.</p><ol>{['Describe the idea','Approve the direction','Try it. Publish it. Evolve it.'].map((item,i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ol><div className="auth-signature"><PulseMark/><span>YOUR IDEAS. YOUR DECISIONS.<br/>ONE CONTINUOUS WORKSPACE.</span></div></aside><section className="auth-card" aria-labelledby="auth-title"><span className="meta">{signup?'YOUR FIRST CHAPTER':'WELCOME BACK'}</span><h1 id="auth-title">{signup?'Create your account':'Sign in to F01'}</h1><p>{signup?'Start with an idea. Keep every version in one place.':'Your projects and their next chapter are waiting.'}</p>{error&&<div className="auth-notice" role="alert">{messages[error]??messages.unavailable}</div>}{signedOut&&<div className="auth-notice" role="status">You’re signed out of F01.</div>}{!options.available&&<div className="auth-notice" role="alert">Sign-in is temporarily unavailable. Please try again shortly.</div>}
 {options.oidc?<div className="auth-methods" aria-busy={Boolean(pending)}>{options.google&&choice('google','Continue with Google',true)}{options.email&&<>{options.google&&<div className="auth-divider"><span>or</span></div>}{choice('email','Continue with Email',!options.google)}<p className="auth-help">A secure magic link, delivered by our identity provider. Open it in the same browser you use here.</p></>}{!options.google&&!options.email&&choice('hosted','Sign in securely',true)}<p className="auth-help">You’ll continue to the secure identity provider. F01 never asks for or stores your password.</p></div>:<div className="auth-methods"><div className="auth-notice">Local review workspace · production login is not configured.</div><Link href={authDestination(returnTo)} className="button button-primary auth-choice">Open development workspace ↗</Link></div>}
 {pending&&<p className="auth-loading" role="status"><span className="auth-spinner" aria-hidden="true"/>Opening the identity provider…</p>}<p className="auth-switch">{signup?'Already have an account?':'New to F01?'} <Link href={`${signup?'/sign-in':'/sign-up'}?returnTo=${encodeURIComponent(authDestination(returnTo))}`}>{signup?'Sign in':'Create an account'}</Link></p><details className="auth-recovery"><summary>Having trouble signing in?</summary><p>Use a new link in the browser where you requested it. If your session expired, sign in again; your saved project and build history remain available.</p><p>Google and email can have separate provider identities. F01 never combines accounts just because their email addresses match.</p></details></section></div><footer className="auth-footer">F01 / FROM FIRST IDEA TO NEXT VERSION</footer></main>;
}
