"""Phase 2A identity, sessions and planning. Frozen additive DDL."""
from alembic import op

revision = "0002_phase2a"
down_revision = "0001_phase1"
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.execute('CREATE TABLE external_identities (\n\tid UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tissuer VARCHAR(500) NOT NULL, \n\tsubject VARCHAR(200) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_external_identities PRIMARY KEY (id), \n\tCONSTRAINT uq_external_identities_issuer_subject UNIQUE (issuer, subject), \n\tCONSTRAINT fk_external_identities_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)\n)')
    op.execute('CREATE TABLE auth_flows (\n\tid UUID NOT NULL, \n\tstate_hash VARCHAR(64) NOT NULL, \n\tbinding_hash VARCHAR(64) NOT NULL, \n\tnonce_hash VARCHAR(64) NOT NULL, \n\tverifier_encrypted TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tconsumed_at TIMESTAMP WITH TIME ZONE, \n\tCONSTRAINT pk_auth_flows PRIMARY KEY (id), \n\tCONSTRAINT uq_auth_flows_state_hash UNIQUE (state_hash)\n)')
    op.execute('CREATE INDEX ix_auth_flows_created_at ON auth_flows (created_at)')
    op.execute('CREATE TABLE auth_sessions (\n\tid UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tsession_hash VARCHAR(64) NOT NULL, \n\tcsrf_hash VARCHAR(64) NOT NULL, \n\taccess_hash VARCHAR(64) NOT NULL, \n\taccess_encrypted TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tCONSTRAINT pk_auth_sessions PRIMARY KEY (id), \n\tCONSTRAINT fk_auth_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id), \n\tCONSTRAINT uq_auth_sessions_session_hash UNIQUE (session_hash)\n)')
    op.execute("CREATE TABLE planning_attempts (\n\tid UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tproject_id UUID, \n\tkey VARCHAR(200) NOT NULL, \n\trequest_hash VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tcontext JSONB NOT NULL, \n\treserved_tokens INTEGER NOT NULL, \n\tinput_tokens INTEGER, \n\toutput_tokens INTEGER, \n\terror_code VARCHAR(100), \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tdeadline_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tCONSTRAINT pk_planning_attempts PRIMARY KEY (id), \n\tCONSTRAINT uq_planning_attempts_user_id_key UNIQUE (user_id, key), \n\tCONSTRAINT uq_planning_attempts_id_user_id_project_id UNIQUE (id, user_id, project_id), \n\tCONSTRAINT fk_attempt_owner FOREIGN KEY(project_id, user_id) REFERENCES projects (id, owner_user_id), \n\tCONSTRAINT ck_planning_attempts_budget_status CHECK (status IN ('pending','succeeded','failed','stale','canceled','abandoned') AND reserved_tokens > 0), \n\tCONSTRAINT fk_planning_attempts_user_id_users FOREIGN KEY(user_id) REFERENCES users (id), \n\tCONSTRAINT fk_planning_attempts_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id)\n)")
    op.execute('CREATE INDEX ix_planning_budget ON planning_attempts (user_id, created_at)')
    op.execute('CREATE TABLE planning_proposals (\n\tid UUID NOT NULL, \n\tattempt_id UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\trequest_id UUID NOT NULL, \n\tbrain_revision_id UUID NOT NULL, \n\tversion_id UUID, \n\tkind VARCHAR(20) NOT NULL, \n\tcontext JSONB NOT NULL, \n\tcontent JSONB NOT NULL, \n\tprovider VARCHAR(100) NOT NULL, \n\tmodel VARCHAR(100) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_planning_proposals PRIMARY KEY (id), \n\tCONSTRAINT uq_planning_proposals_attempt_id UNIQUE (attempt_id), \n\tCONSTRAINT uq_planning_proposals_project_id_id UNIQUE (project_id, id), \n\tCONSTRAINT uq_planning_proposals_id_user_id UNIQUE (id, user_id), \n\tCONSTRAINT fk_proposal_attempt FOREIGN KEY(attempt_id, user_id, project_id) REFERENCES planning_attempts (id, user_id, project_id), \n\tCONSTRAINT fk_planning_owner FOREIGN KEY(project_id, user_id) REFERENCES projects (id, owner_user_id), \n\tCONSTRAINT fk_planning_proposals_attempt_id_planning_attempts FOREIGN KEY(attempt_id) REFERENCES planning_attempts (id), \n\tCONSTRAINT fk_planning_proposals_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id), \n\tCONSTRAINT fk_planning_proposals_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)\n)')
    op.execute('CREATE TABLE plan_reviews (\n\tid UUID NOT NULL, \n\tproposal_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_plan_reviews PRIMARY KEY (id), \n\tCONSTRAINT uq_plan_reviews_proposal_id UNIQUE (proposal_id), \n\tCONSTRAINT fk_review_owner FOREIGN KEY(proposal_id, user_id) REFERENCES planning_proposals (id, user_id), \n\tCONSTRAINT fk_plan_reviews_proposal_id_planning_proposals FOREIGN KEY(proposal_id) REFERENCES planning_proposals (id), \n\tCONSTRAINT fk_plan_reviews_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)\n)')
    op.execute('ALTER TABLE planning_proposals ADD CONSTRAINT fk_brain_revision_id_brain_revisions FOREIGN KEY(project_id, brain_revision_id) REFERENCES brain_revisions (project_id, id) DEFERRABLE INITIALLY DEFERRED')
    op.execute('ALTER TABLE planning_proposals ADD CONSTRAINT fk_request_id_project_requests FOREIGN KEY(project_id, request_id) REFERENCES project_requests (project_id, id) DEFERRABLE INITIALLY DEFERRED')
    op.execute('ALTER TABLE planning_proposals ADD CONSTRAINT fk_version_id_project_versions FOREIGN KEY(project_id, version_id) REFERENCES project_versions (project_id, id) DEFERRABLE INITIALLY DEFERRED')
    op.execute('CREATE TRIGGER immutable_external_identities BEFORE UPDATE OR DELETE ON external_identities FOR EACH ROW EXECUTE FUNCTION f01_immutable_history()')
    op.execute('CREATE TRIGGER immutable_planning_proposals BEFORE UPDATE OR DELETE ON planning_proposals FOR EACH ROW EXECUTE FUNCTION f01_immutable_history()')
    op.execute('CREATE TRIGGER immutable_plan_reviews BEFORE UPDATE OR DELETE ON plan_reviews FOR EACH ROW EXECUTE FUNCTION f01_immutable_history()')

def downgrade() -> None:
    op.execute('DROP TABLE plan_reviews CASCADE')
    op.execute('DROP TABLE planning_proposals CASCADE')
    op.execute('DROP TABLE planning_attempts CASCADE')
    op.execute('DROP TABLE auth_sessions CASCADE')
    op.execute('DROP TABLE auth_flows CASCADE')
    op.execute('DROP TABLE external_identities CASCADE')
