'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {readIntentDraft,saveIntentDraft} from '@/lib/workspace/intent-draft';
import type {Requests} from '@/lib/workspace/contracts';
import {useWorkspace,useResource,ResourceState} from './workspace';
import {useFlow} from './flow';
export function ConversationPanel(){
 const {id,snapshot}=useWorkspace(),flow=useFlow(),router=useRouter(),requests=useResource<Requests>(`/projects/${id}/requests`);
 const [text,setText]=useState(''),[error,setError]=useState('');const restored=useRef(false);
 const owner=flow.session.data?.principal.id,plan=flow.plans.data?.items[0],active=Boolean(flow.currentRun&&['queued','running'].includes(flow.currentRun.status));
 useEffect(()=>{if(!owner||restored.current)return;restored.current=true;try{const draft=readIntentDraft(sessionStorage,id,owner);if(draft)setText(draft.text);}catch{}},[id,owner]);
 function review(event:React.FormEvent){event.preventDefault();if(!owner||active||text.trim().length<20)return;const draft={project:id,owner,brain:snapshot.project.current_brain_revision_id,version:snapshot.project.current_version_id,text};try{if(!saveIntentDraft(sessionStorage,draft)){setError('Your draft could not be carried to planning. Copy it, then open Planning.');return;}router.push(`/projects/${id}/planning?change=1`);}catch{setError('Your text is preserved here. Open Planning to continue.');}}
 return <aside className="conversation-panel" aria-label="Project conversation"><div className="conversation-heading"><span aria-hidden="true">F01</span><div><h2>Your direction, made real.</h2><p>Saved requests and proposed work</p></div></div><div className="conversation-messages"><ResourceState {...requests}/>{requests.data?.items.slice(0,2).reverse().map(request=><div className="conversation-message user-message" key={request.id}><span className="meta">YOU · {request.kind==='initial'?'ORIGINAL BRIEF':'SAVED CHANGE'}</span><p>{request.text}</p></div>)}<div className="conversation-message"><span className="meta">F01 · {plan?plan.current_context?'PROPOSED PLAN':'EARLIER PLAN':'NEXT STEP'}</span><p>{plan?plan.content.plan.product_summary:'Review a plan before building. Your application will appear here after its checks pass.'}</p><Link href={`/projects/${id}/planning`}>{plan?'Open plan & approval':'Make your first plan'} ↗</Link></div></div><form className="conversation-composer" onSubmit={review}><label htmlFor="workspace-intent">What should change?</label><textarea id="workspace-intent" value={text} onChange={event=>{setText(event.target.value);setError('');}} maxLength={10000} rows={4} disabled={active||Boolean(snapshot.project.archived_at)} placeholder="Add a priority filter. Keep the layout simple."/><p>{active?'Your build is in progress. You can plan another change when it finishes.':'Describe a change, then review its plan before a new build.'}</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-secondary" disabled={!owner||active||Boolean(snapshot.project.archived_at)||text.trim().length<20}>Review this change ↗</button></form></aside>;
}
