'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {readIntentDraft,saveIntentDraft} from '@/lib/workspace/intent-draft';
import type {Requests} from '@/lib/workspace/contracts';
import {useWorkspace,useResource,ResourceState} from './workspace';
import {useFlow} from './flow';
export function ConversationPanel(){
 const {id,snapshot}=useWorkspace(),flow=useFlow(),router=useRouter(),query=useSearchParams(),requests=useResource<Requests>(`/projects/${id}/requests`);
 const [text,setText]=useState(''),[error,setError]=useState(''),[expanded,setExpanded]=useState(true),[restoredFor,setRestoredFor]=useState('');
 const base=useRef<{brain:string;version:string|null}|null>(null);
 const owner=flow.session.data?.principal.id,plan=flow.plans.data?.items[0],active=Boolean(flow.currentRun&&['queued','running'].includes(flow.currentRun.status));
 const owned=Boolean(owner&&owner===snapshot.project.owner_user_id),ready=owned&&restoredFor===`${id}:${owner}`,historical=Boolean(query.get('version'));
 const locked=!ready||Boolean(flow.session.error)||historical||active||Boolean(snapshot.project.archived_at);
 useEffect(()=>{const media=matchMedia('(max-width:1000px)');const update=()=>setExpanded(!media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{if(!owner||!owned||restoredFor===`${id}:${owner}`)return;let draft=null;try{draft=readIntentDraft(sessionStorage,id,owner);}catch{}setText(draft?.text??'');base.current=draft?{brain:draft.brain,version:draft.version}:{brain:snapshot.project.current_brain_revision_id,version:snapshot.project.current_version_id};setRestoredFor(`${id}:${owner}`);},[id,owner,owned,restoredFor,snapshot.project.current_brain_revision_id,snapshot.project.current_version_id]);
 function edit(value:string){if(locked||!owner)return;if(!text)base.current={brain:snapshot.project.current_brain_revision_id,version:snapshot.project.current_version_id};setText(value);const context=base.current!;try{setError(saveIntentDraft(sessionStorage,{project:id,owner,...context,text:value})?'':'This browser cannot keep your draft after a reload. Your text is still here; copy it before leaving.');}catch{setError('Your text is still here. Copy it before leaving this page.');}}
 function review(event:React.FormEvent){event.preventDefault();if(locked||!owner||Array.from(text.trim()).length<20)return;const draft={project:id,owner,...base.current!,text};try{if(!saveIntentDraft(sessionStorage,draft)){setError('Your draft could not be carried to planning. Copy it, then open Planning.');return;}router.push(`/projects/${id}/planning?change=1`);}catch{setError('Your text is preserved here. Open Planning to continue.');}}
 return <aside className="conversation-panel" aria-label="Project conversation"><details open={expanded} onToggle={event=>setExpanded(event.currentTarget.open)}><summary className="conversation-heading"><span aria-hidden="true">F01</span><div><h2>Your direction, made real.</h2><p>Saved requests and proposed work</p></div></summary><div className="conversation-messages"><ResourceState {...requests}/>{requests.data?.items.slice(0,2).reverse().map(request=><div className="conversation-message user-message" key={request.id}><span className="meta">YOU · {request.kind==='initial'?'ORIGINAL BRIEF':'SAVED CHANGE'}</span><p>{request.text}</p></div>)}<div className="conversation-message"><span className="meta">F01 · {plan?plan.current_context?'PROPOSED PLAN':'EARLIER PLAN':'NEXT STEP'}</span><p>{plan?plan.content.plan.product_summary:'Review a plan before building. Your application will appear here after its checks pass.'}</p><Link href={`/projects/${id}/planning`}>{plan?'Open plan & approval':'Make your first plan'} ↗</Link></div></div><form className="conversation-composer" onSubmit={review}><label htmlFor="workspace-intent">What should change?</label><textarea id="workspace-intent" value={ready?text:''} onChange={event=>edit(event.target.value)} maxLength={10000} rows={4} disabled={locked} aria-describedby="conversation-context" placeholder="Add a priority filter. Keep the layout simple."/><p id="conversation-context">{historical?<><span>Historical preview is read-only.</span> <Link href={`/projects/${id}`}>Return to the current version to plan a change.</Link></>:owner&&!owned?'This workspace belongs to another account.':flow.session.error?'Workspace access needs attention.':!ready?'Restoring your saved change…':active?'Your build is in progress. You can plan another change when it finishes.':'Describe a change, then review its plan before a new build.'}</p>{flow.session.error&&<p className="form-error" role="alert">{flow.session.error}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-secondary" disabled={locked||Array.from(text.trim()).length<20}>Review this change ↗</button></form></details></aside>;
}
