'use client';
import { useState } from 'react';
import { fixturePath, type Descriptor } from '@/lib/workspace/contracts';
export function PreviewFrame({ descriptor, viewport }: { descriptor: Descriptor; viewport: 'desktop' | 'tablet' | 'phone' }) {
  const [key, setKey] = useState(0), [loadedFrame, setLoadedFrame] = useState(''); const path = descriptor.kind === 'fixture' ? fixturePath(descriptor) : isolatedPreviewPath(descriptor.url,descriptor.expires_at);
  const frameKey = `${path}-${key}`;
  if (!path) return <p role="alert">This preview is unavailable or expired. Inspect its saved version and verification records.</p>;
  return <><div className="preview-frame-status"><span className="meta">{descriptor.kind === 'fixture' ? 'SYNTHETIC FIXTURE' : 'REAL PREVIEW'} / {descriptor.kind === 'fixture' ? descriptor.fixture_id : 'VERIFIED ISOLATED APP'}</span><button className="button button-quiet" onClick={() => setKey(n => n + 1)}>Reload preview</button></div>{loadedFrame !== frameKey && <p role="status">Loading isolated sample…</p>}<div className={`preview-frame-wrap viewport-${viewport}`}><iframe key={frameKey} src={path} title={descriptor.kind === 'fixture' ? `Synthetic ${descriptor.fixture_id === 'crm-v1' ? 'CRM' : 'generic'} preview` : 'Verified generated application preview'} sandbox="allow-scripts" referrerPolicy="no-referrer" onLoad={() => setLoadedFrame(frameKey)} /></div></>;
}
export function isolatedPreviewPath(value: string, expires: string): string | null {
  try { const url = new URL(value); if(Date.parse(expires)<=Date.now()||!['http:','https:'].includes(url.protocol)||url.username||url.password||url.search||url.hash||!/^\/p\/[a-f0-9-]{36}\/[A-Za-z0-9_-]{43}\/$/.test(url.pathname)) return null; if(typeof window !== 'undefined' && url.hostname === window.location.hostname)return null;return url.href; } catch { return null; }
}
export function ViewportControl({ value, onChange }: { value: 'desktop' | 'tablet' | 'phone'; onChange: (v: 'desktop' | 'tablet' | 'phone') => void }) { return <div className="viewport-controls" role="group" aria-label="Preview viewport">{(['desktop', 'tablet', 'phone'] as const).map(v => <button key={v} aria-pressed={value === v} onClick={() => onChange(v)}>{v[0]!.toUpperCase() + v.slice(1)}</button>)}</div>; }
export function FixtureShowcase() { const [fixture, setFixture] = useState<'crm-v1' | 'generic-v1'>('crm-v1'), [viewport, setViewport] = useState<'desktop' | 'tablet' | 'phone'>('desktop'); return <div className="page fixture-showcase"><span className="meta">DEVELOPMENT COMPONENT SHOWCASE / SYNTHETIC DATA</span><h1>Sample preview foundations</h1><p>These bundled samples are independent of your projects. They were not generated from a brief, built, tested or deployed by the platform. Sample interactions stay inside the isolated frame.</p><div className="preview-toolbar"><label htmlFor="fixture-select">Sample fixture</label><select id="fixture-select" value={fixture} onChange={e => setFixture(e.target.value as typeof fixture)}><option value="crm-v1">CRM sample</option><option value="generic-v1">Generic sample</option></select><ViewportControl value={viewport} onChange={setViewport} /></div><PreviewFrame descriptor={{ kind: 'fixture', fixture_id: fixture }} viewport={viewport} /></div>; }
