'use client';
import { useEffect, useState } from 'react';
import { fixturePath, type Descriptor } from '@/lib/workspace/contracts';
import { isolatedPreviewPath, isolatedBrowserPath } from '@/lib/workspace/preview-url';
export function PreviewFrame({ descriptor, viewport, projectId }: { descriptor: Descriptor; viewport: 'desktop' | 'tablet' | 'phone'; projectId?: string }) {
  const [factoryHost, setFactoryHost] = useState('');
  useEffect(() => setFactoryHost(window.location.hostname), []);
  const [, checkExpiry] = useState(0);
  const expires = descriptor.kind === 'isolated' ? descriptor.expires_at : null;
  useEffect(() => { if (!expires) return; const remaining = Date.parse(expires) - Date.now(); if (!Number.isFinite(remaining) || remaining <= 0) return; const timer = setTimeout(() => checkExpiry(n => n + 1), Math.min(remaining + 1, 2147483647)); return () => clearTimeout(timer); }, [expires]);
  const [key, setKey] = useState(0), [loadedFrame, setLoadedFrame] = useState(''); const path = descriptor.kind === 'fixture' ? fixturePath(descriptor) : isolatedPreviewPath(descriptor.url,descriptor.expires_at);
  const browserPath = descriptor.kind === 'isolated' && projectId ? isolatedBrowserPath(descriptor.browser_url, descriptor.url, descriptor.expires_at, projectId, factoryHost) : null;
  const frameKey = `${path}-${key}`;
  if (!path) return <div className="workspace-empty-surface preview-unavailable" role="alert"><h3>Preview unavailable</h3><p>This preview is unavailable or expired. Inspect its saved version and verification records.</p></div>;
  return <>{browserPath && <p className="preview-context-note">Open the application in its own tab to save browser data across versions. This embedded preview uses isolated, temporary state.</p>}<div className="preview-frame-status"><span className="preview-browser-dots" aria-hidden="true"><i/><i/><i/></span><span className="meta">{descriptor.kind === 'fixture' ? 'SYNTHETIC FIXTURE' : 'REAL PREVIEW'} / {descriptor.kind === 'fixture' ? descriptor.fixture_id : 'VERIFIED ISOLATED APP'}</span><span className="preview-toolbar-actions">{browserPath && <a className="button button-secondary" href={browserPath} target="_blank" rel="noopener noreferrer">Open application ↗</a>}<button className="button button-quiet" onClick={() => setKey(n => n + 1)}>Reload preview</button></span></div>{loadedFrame !== frameKey && <p role="status">{descriptor.kind === 'fixture' ? 'Loading isolated sample…' : 'Loading your application preview…'}</p>}<div className={`preview-frame-wrap viewport-${viewport}`}><iframe key={frameKey} src={path} title={descriptor.kind === 'fixture' ? `Synthetic ${descriptor.fixture_id === 'crm-v1' ? 'CRM' : 'generic'} preview` : 'Verified generated application preview'} sandbox="allow-scripts" referrerPolicy="no-referrer" onLoad={() => setLoadedFrame(frameKey)} /></div></>;
}
export function ViewportControl({ value, onChange }: { value: 'desktop' | 'tablet' | 'phone'; onChange: (v: 'desktop' | 'tablet' | 'phone') => void }) { return <div className="viewport-controls" role="group" aria-label="Preview viewport">{(['desktop', 'tablet', 'phone'] as const).map(v => <button key={v} aria-pressed={value === v} onClick={() => onChange(v)}>{v[0]!.toUpperCase() + v.slice(1)}</button>)}</div>; }
export function FixtureShowcase() { const [fixture, setFixture] = useState<'crm-v1' | 'generic-v1'>('crm-v1'), [viewport, setViewport] = useState<'desktop' | 'tablet' | 'phone'>('desktop'); return <div className="page fixture-showcase"><span className="meta">DEVELOPMENT COMPONENT SHOWCASE / SYNTHETIC DATA</span><h1>Sample preview foundations</h1><p>These bundled samples are independent of your projects. They were not generated from a brief, built, tested or deployed by the platform. Sample interactions stay inside the isolated frame.</p><div className="preview-toolbar"><label htmlFor="fixture-select">Sample fixture</label><select id="fixture-select" value={fixture} onChange={e => setFixture(e.target.value as typeof fixture)}><option value="crm-v1">CRM sample</option><option value="generic-v1">Generic sample</option></select><ViewportControl value={viewport} onChange={setViewport} /></div><PreviewFrame descriptor={{ kind: 'fixture', fixture_id: fixture }} viewport={viewport} /></div>; }
