'use client';
import { useEffect, useRef, useState } from 'react';
import { projectRequest, ProjectAPIError } from '@/lib/projects/browser';
import { outcomeIsUnknown } from '@/lib/projects/creation';
import { changeInput, readChangeAttempt, uuid, type ChangeAttempt, type Requests, type RequestRecord } from '@/lib/workspace/contracts';
import { useWorkspace, useResource, ResourceState, time } from './workspace';
export function RequestHistory() {
  const { id } = useWorkspace(); const [cursor, setCursor] = useState('');
  const result = useResource<Requests>(`/projects/${id}/requests${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ''}`);
  return <section className="request-history" aria-label="Saved request history"><div className="section-heading"><h2>Saved requests</h2><span className="meta">IMMUTABLE / SERVER RECORDS</span></div><ResourceState {...result} />{result.data?.items.map(record => <RequestCard key={record.id} record={record} />)}{result.data?.items.length === 0 && <p>No saved requests.</p>}<div className="record-pagination">{cursor && <button className="button button-quiet" onClick={() => setCursor('')}>Latest requests</button>}{result.data?.next_cursor && <button className="button button-secondary" onClick={() => setCursor(result.data!.next_cursor!)}>Older requests</button>}</div></section>;
}
export function RequestCard({ record }: { record: RequestRecord }) { const { snapshot,runCommands } = useWorkspace(); const eligible = record.kind === 'change' && record.base_brain_revision_id === snapshot.project.current_brain_revision_id && record.base_version_id === snapshot.project.current_version_id && !snapshot.active_run && !snapshot.project.archived_at; return <article className="request-record"><div className="record-heading"><strong>{record.kind === 'initial' ? 'Original brief' : 'Change request'}</strong><time dateTime={record.created_at}>{time(record.created_at)}</time></div><p className="preserved-text">{record.text}</p><details><summary>Saved context and authorship</summary><dl><dt>Request ID</dt><dd>{record.id}</dd><dt>Author ID</dt><dd>{record.created_by}</dd><dt>Base Brain</dt><dd>{record.base_brain_revision_id ?? 'Initial brief · no base'}</dd><dt>Base version</dt><dd>{record.base_version_id ?? 'No completed version'}</dd></dl></details>{record.kind === 'change' && <p className="record-disclosure">Recorded intent. No execution or Brain revision was produced by saving it.</p>}{eligible && <button className="button button-secondary" disabled={runCommands.pending || Boolean(runCommands.recovery)} onClick={() => void runCommands.start(record.id,record.base_brain_revision_id!)}>Simulate saved request</button>}</article>; }
export function RequestDrawer() {
  const { id, snapshot, refresh, runCommands } = useWorkspace();
  const [text, setText] = useState(''), [pending, setPending] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [review, setReview] = useState(false), [unknown, setUnknown] = useState(false), [ready, setReady] = useState(false);
  const [simulate, setSimulate] = useState(false);
  const [base, setBase] = useState({ brain: snapshot.project.current_brain_revision_id, version: snapshot.project.current_version_id });
  const attempt = useRef<ChangeAttempt | null>(null), busy = useRef(false); const storageKey = `f01.pending-change.v1.${id}`;
  useEffect(() => { let receipt: ChangeAttempt | null = null; try { receipt = readChangeAttempt(sessionStorage, storageKey); } catch { /* memory recovery remains */ }
    if (receipt) { attempt.current = receipt; setText(receipt.input.text); setBase({ brain: receipt.input.base_brain_revision_id, version: receipt.input.base_version_id }); setSimulate(Boolean(receipt.simulate)); setUnknown(true); } setReady(true);
  }, [storageKey]);
  function forget() { attempt.current = null; try { sessionStorage.removeItem(storageKey); } catch { /* keep no inventory */ } }
  async function save() {
    if (busy.current || !ready) return;
    const data = changeInput(text, base.brain, base.version); if (!data) { setError('Enter a change request of 20–10,000 characters.'); return; }
    if (attempt.current && Date.now() - attempt.current.started >= 86400000) { setError('This unresolved request is older than the 24-hour recovery window. Check saved request history before starting another request.'); return; }
    const command = attempt.current ?? { key: crypto.randomUUID(), input: data, started: Date.now(), simulate }; attempt.current = command;
    try { sessionStorage.setItem(storageKey, JSON.stringify(command)); } catch { /* stable mounted receipt */ }
    busy.current = true; setPending(true); setError(''); setNotice('');
    try { const saved = await projectRequest<RequestRecord>(`/projects/${id}/requests`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': command.key }, body: JSON.stringify(command.input) });
      if (!uuid.test(saved.id) || saved.project_id !== id.toLowerCase() || saved.kind !== 'change' || saved.text !== command.input.text || saved.base_brain_revision_id !== command.input.base_brain_revision_id || saved.base_version_id !== command.input.base_version_id) throw new ProjectAPIError('SERVICE_UNAVAILABLE', 0);
      forget(); setUnknown(false); setText(''); setNotice('Change request recorded. The original brief and Brain are unchanged. No execution started.'); const current = await refresh(); if (current) setBase({ brain: current.project.current_brain_revision_id, version: current.project.current_version_id });
      if (command.simulate) { const run = await runCommands.start(saved.id, command.input.base_brain_revision_id); setNotice(run ? 'Change request saved and Simulation queued. The original brief is unchanged; the bundled sample may remain unchanged.' : 'Change request saved. The demonstration was not confirmed. Inspect saved requests and the simulation command result.'); }
    } catch (e) { const unresolved = !(e instanceof ProjectAPIError) || outcomeIsUnknown(e.status, e.code) || e.code === 'IDEMPOTENCY_KEY_REUSED'; setUnknown(unresolved); if (!unresolved) forget(); if (e instanceof ProjectAPIError && ['STALE_BRAIN_REVISION', 'STALE_BASE_VERSION'].includes(e.code)) setReview(true); setError(e instanceof Error ? e.message : 'Unable to confirm this request.'); }
    finally { busy.current = false; setPending(false); }
  }
  async function reviewContext() { setPending(true); const current = await refresh(); if (current) { setBase({ brain: current.project.current_brain_revision_id, version: current.project.current_version_id }); setReview(false); setError(''); setNotice(`Current Brain revision ${current.current_brain.revision} reviewed. Your draft is preserved. Inspect Brain and the current version, then record your request when ready.`); } setPending(false); }
  useEffect(() => { if (ready && !text.trim() && !unknown && !attempt.current) { setBase(value => value.brain === snapshot.project.current_brain_revision_id && value.version === snapshot.project.current_version_id ? value : { brain: snapshot.project.current_brain_revision_id, version: snapshot.project.current_version_id }); setReview(false); } }, [ready,text,unknown,snapshot.project.current_brain_revision_id,snapshot.project.current_version_id]);
  const stale = review || (!unknown && (base.brain !== snapshot.project.current_brain_revision_id || base.version !== snapshot.project.current_version_id));
  const locked = pending || unknown;
  return <div className="request-drawer-body"><form className="request-composer" onSubmit={e => { e.preventDefault(); void save(); }} aria-busy={pending}>
    <span className="meta">CHANGE / RECORDED INTENT</span><h2>What should change?</h2><p>Save a request against this project’s context. Your original brief stays intact.</p><label htmlFor="change-text">Change request</label><textarea id="change-text" value={text} readOnly={locked} onChange={e => { if (!text && !attempt.current) setBase({ brain: snapshot.project.current_brain_revision_id, version: snapshot.project.current_version_id }); setText(e.target.value); }} rows={5} aria-describedby="change-context" />
    <p id="change-context" className="context-reference">Base Brain: {base.brain}<br />Base version: {base.version ?? 'None · no completed version'}</p>
    {snapshot.active_run && <p className="workspace-notice">A demonstration is {snapshot.active_run.status}. New requests must wait until it ends. Cancel it in Run details or wait for its terminal outcome.</p>}{snapshot.project.archived_at && <p className="workspace-notice">Unarchive this project before recording a change.</p>}
    {unknown && <p role="status">Save awaiting confirmation. Retry uses the exact same text, context and key.</p>}{stale && <div className="workspace-notice"><p>Your draft context is stale. Review the current project before recording it.</p><button type="button" className="button button-secondary" disabled={pending} onClick={() => void reviewContext()}>Review current context</button></div>}
    <label className="simulation-option"><input type="checkbox" checked={simulate} disabled={locked} onChange={e => setSimulate(e.target.checked)} /> Run an optional demonstration after saving</label><p className="record-disclosure">Simulation selects a bundled fixture. Arbitrary changes may leave its interface unchanged. No code, tests, fixes or external deployment.</p>
    {error && <p role="alert" className="form-error">{error}</p>}{notice && <p role="status">{notice}</p>}<button className="button button-primary" disabled={!ready || pending || stale || (!unknown && Boolean(snapshot.active_run || snapshot.project.archived_at))}>{pending ? 'Recording request…' : unknown ? 'Retry saved request' : simulate ? 'Record and simulate' : 'Record change request'}</button><p className="record-disclosure">Recording alone leaves Brain and preview unchanged. Demonstrations run separately.</p>
  </form><RequestHistory /></div>;
}
