'use client';
import Link from 'next/link';
import { useSearchParams, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ProjectSettings } from '@/features/projects/project-settings';
import type { Session } from '@/lib/projects/contracts';
import type { Brain, Revisions, Provenance, Statement, Events, Versions, Version } from '@/lib/workspace/contracts';
import { useWorkspace, useResource, ResourceState, time } from './workspace';
import { RequestHistory, RequestCard } from './requests';
import { ReleasePanel } from './releases';
import { RealBuildPanel } from './real-build';
import { PreviewFrame, ViewportControl } from './preview';
import {useFlow,useJourney} from './flow';
export function PreviewView() {
  const {id,snapshot,viewport,setViewport,setInspectedVersion}=useWorkspace(),journey=useJourney(),flow=useFlow(),query=useSearchParams(),router=useRouter();
  const versionId=query.get('version'),focus=query.get('step');
  const selected=useResource<Version>(versionId?`/projects/${id}/versions/${encodeURIComponent(versionId)}`:null);
  const version=versionId?selected.data:snapshot.current_version;
  const [buildReady,setBuildReady]=useState(false),[buildAttention,setBuildAttention]=useState(false),[releaseAttention,setReleaseAttention]=useState(false);
  const [buildOpen,setBuildOpen]=useState(!snapshot.current_version),[publishOpen,setPublishOpen]=useState(focus==='deploy');
  const demo=flow.session.data?.capabilities?.execution_mode==='simulated'&&snapshot.active_run?.mode!=='real';
  useEffect(()=>{setInspectedVersion(version?.number??null);return()=>setInspectedVersion(null);},[version?.number,setInspectedVersion]);
  useEffect(()=>{if(focus==='build'||snapshot.active_run||buildReady||buildAttention)setBuildOpen(true);else if(snapshot.current_version)setBuildOpen(false);},[focus,snapshot.active_run?.id,snapshot.current_version?.id,buildReady,buildAttention]);
  useEffect(()=>{if(focus==='deploy'||journey.activeRelease||releaseAttention)setPublishOpen(true);else if(focus!== 'deploy')setPublishOpen(false);},[focus,journey.activeRelease?.id,releaseAttention]);
  const buildPrimary=!version||Boolean(snapshot.active_run)||buildReady||buildAttention||focus==='build';
  function publishing(open:boolean){setPublishOpen(open);const params=new URLSearchParams(query.toString());if(open)params.set('step','deploy');else params.delete('step');router.replace(`/projects/${id}${params.size?'?'+params:''}`,{scroll:false});}
  return <section className="workspace-preview" aria-labelledby="preview-title">
    {!versionId&&<details className={`build-pane ${buildPrimary?'focus-pane':''}`} open={buildOpen} onToggle={e=>setBuildOpen(e.currentTarget.open)}><summary>{snapshot.active_run?'Build in progress':buildReady?'Ready to build':buildAttention?'Build needs attention':version?'Build details':'Start your project'}</summary><RealBuildPanel onReadyChange={setBuildReady} onAttentionChange={setBuildAttention}/>{snapshot.active_run?.mode==='simulated'&&<div className="workspace-notice"><h2>Demonstration in progress</h2><p>Saved demonstration steps are running. This does not generate an application.</p><Link className="button button-primary" href={`/projects/${id}?panel=trace`}>Follow Build Trace</Link></div>}</details>}
    {!versionId&&version?.mode==='real'&&<details className={`publish-pane ${focus==='deploy'?'focus-pane':''}`} open={publishOpen} onToggle={e=>{if(e.currentTarget.open!==publishOpen)publishing(e.currentTarget.open);}}><summary className={!publishOpen&&!buildPrimary?'publish-entry':''}>{journey.activeRelease?'Publishing progress':journey.currentLive?'Live release & publishing':'Publish this version'}</summary><ReleasePanel secondaryActions={buildPrimary&&focus!=='deploy'} onAttentionChange={setReleaseAttention}/></details>}
    <div className="preview-surface"><div className="preview-toolbar"><div><span className="meta">{versionId?'VERSION HISTORY':version?.mode==='real'?'VERIFIED APPLICATION':'PRODUCT PREVIEW'}</span><h2 id="preview-title">{version?`${version.mode==='real'?'Version':'Demo version'} ${version.number}`:'Preview pending.'}</h2></div>{version&&<div className="preview-toolbar-actions"><ViewportControl value={viewport} onChange={setViewport}/>{!versionId&&version.mode==='real'&&!buildPrimary&&!publishOpen&&!journey.currentLive&&<Link className="button button-primary" href={`/projects/${id}?step=deploy`}>Continue to publish</Link>}</div>}</div>
      {versionId&&<><ResourceState {...selected}/><Link className="text-action" href={`/projects/${id}`}>Return to current preview ↗</Link></>}
      {snapshot.latest_run?.status==='failed'&&snapshot.current_version&&<p className="preserved-version">Latest update needs attention. Version {snapshot.current_version.number} remains current and available. <Link className="text-action" href={`/projects/${id}?panel=run`}>Inspect the failed attempt ↗</Link></p>}
      {version?<><p className="preview-context-note">{version.mode==='real'?'Verified application preview. Preview and production are separate.':version.id===snapshot.project.current_version_id?'Current successful demo version. This is a curated sample.':'Historical demo version · inspection only.'}</p><PreviewFrame descriptor={version.preview_descriptor} viewport={viewport}/></>:!versionId&&<div className="preview-not-yet"><span className="pending-registration" aria-hidden="true"><i/><i/><i/></span><p>{snapshot.active_run?'Your preview will appear here after verification succeeds.':demo?'Your project is saved. A completed demonstration will appear here.':'Your brief is saved. Make a plan, approve it, then build your first version.'}</p></div>}
    </div>
    {!versionId&&journey.currentLive&&!buildPrimary&&!publishOpen&&<div className="next-change"><div><span className="meta">NEXT VERSION</span><h2>What should get better?</h2><p>Your live release stays in place while you work on a change.</p></div><Link className="button button-primary" href={`/projects/${id}/planning?change=1`}>Make a change</Link></div>}
    {versionId&&<ReleasePanel historyOnly versionId={versionId}/>}
  </section>;
}
export function BriefView() {
  const { id, openRequests } = useWorkspace(); const result = useResource<Brain>(`/projects/${id}/brain`); const original = result.data?.context.requests.find(r => r.kind === 'initial');
  return <div className="workspace-document"><DocumentHeading index="01" title="Original brief" description="The intention that started this project. Preserved exactly as saved." /><ResourceState {...result} />{original && <RequestCard record={original} />}<button className="button button-secondary" onClick={openRequests}>Record a change</button><RequestHistory /></div>;
}
export function ProvenanceLabel({ value }: { value: Provenance }) { const label = { user_request: 'User requested', template: 'Template assumption', simulation: 'Simulated outcome', model_proposed: 'Model proposed', generated: 'Generated source', verified: 'Verified evidence', published: 'Published preview' }[value.source]; return <details className={`provenance provenance-${value.source}`}><summary>{label}</summary><span>{value.source === 'user_request' ? `Request ${value.request_id}` : value.source === 'template' ? value.fixture_ref : `Run ${value.run_id} · Event ${value.event_sequence}`}</span></details>; }
function StatementView({ value }: { value: Statement }) { return <div className="brain-statement"><p className="preserved-text">{value.text}</p><ProvenanceLabel value={value.provenance} /></div>; }
function DocumentHeading({ index, title, description }: { index: string; title: string; description: string }) { return <div className="document-heading"><span className="meta">PROJECT DOSSIER / {index}</span><h2>{title}</h2><p>{description}</p></div>; }
export function BrainView() {
  const { id, snapshot } = useWorkspace(), router = useRouter(), query = useSearchParams(); const revision = query.get('revision'); const [cursor, setCursor] = useState('');
  const result = useResource<Brain>(`/projects/${id}/brain${revision ? `?revision=${encodeURIComponent(revision)}` : ''}`), list = useResource<Revisions>(`/projects/${id}/brain/revisions${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ''}`);
  const record = result.data?.revision, content = record?.content;
  return <div className="workspace-document brain-document"><DocumentHeading index="02" title="Project Brain" description="Immutable project knowledge with its sources visible. Requested or proposed content is not proof of implementation." /><div className="brain-revision-controls"><label htmlFor="brain-revision">Inspect revision</label><select id="brain-revision" value={record?.revision ?? ''} onChange={e => router.push(`/projects/${id}/brain?revision=${e.target.value}`)}><option value="" disabled>Choose a revision</option>{record && !list.data?.items.some(item => item.id === record.id) && <option value={record.revision}>Revision {record.revision} · Selected</option>}{list.data?.items.map(r => <option key={r.id} value={r.revision}>Revision {r.revision}{r.id === snapshot.project.current_brain_revision_id ? ' · Current' : ''}</option>)}</select><Link href={`/projects/${id}/brain`}>Current Brain</Link>{cursor && <button onClick={() => setCursor('')}>Latest revisions</button>}{list.data?.next_cursor && <button onClick={() => setCursor(list.data!.next_cursor!)}>Older revisions</button>}</div><ResourceState {...list} /><ResourceState {...result} />
    {record && content && <><div className="revision-metadata"><span className="mode-label">Immutable revision {record.revision}</span><span className="meta">SCHEMA {record.schema_version} / {record.id === snapshot.project.current_brain_revision_id ? 'CURRENT' : 'HISTORICAL INSPECTION'}</span><p>Saved {time(record.created_at)}</p><details><summary>Revision lineage</summary><p>Source request: {record.source_request_id}</p>{record.source_run_id && <p>Source run: {record.source_run_id}</p>}<p>Revision ID: {record.id}</p></details></div>
      <section className="brain-section"><h3>Product summary</h3><StatementView value={content.product.summary} /></section>
      <section className="brain-section"><h3>Requirements</h3>{content.product.requirements.map(r => <article key={r.requirement_id}><div className="entry-meta">{r.requirement_id} / {r.priority} priority{r.assumption ? ' / Details need confirmation' : ''}</div><StatementView value={r} /><h4>Acceptance criteria · proposed</h4>{r.acceptance_criteria.map((a, n) => <StatementView key={n} value={a} />)}</article>)}</section>
      <section className="brain-section"><h3>Ordered plan</h3>{content.plan.map(s => <article key={s.step_id}><div className="entry-meta">{s.step_id} / {s.phase} / {s.status}</div><StatementView value={s} /><p className="context-reference">Requirements: {s.requirement_ids.join(', ')} · Dependencies: {s.dependencies.join(', ') || 'None'}</p></article>)}</section>
      <section className="brain-section"><h3>Architecture · {content.architecture.evidence}</h3><StatementView value={content.architecture.overview} />{content.architecture.component_relationships.map((s, n) => <StatementView key={n} value={s} />)}<h4>Rationale</h4><StatementView value={content.architecture.rationale} /></section>
      <section className="brain-section"><h3>Intended product stack</h3><p>This proposal describes the eventual product, independently of the factory’s implementation.</p>{(['frontend', 'backend', 'database', 'rationale'] as const).map(k => <article key={k}><h4>{k[0]!.toUpperCase() + k.slice(1)}</h4><StatementView value={content.stack[k]} /></article>)}</section>
      <section className="brain-section"><h3>Database proposal</h3>{content.database.entities.length === 0 && <p>No product entities have been confirmed.</p>}{content.database.entities.map(entity => <article key={entity.entity_id}><span className="entry-meta">{entity.entity_id}</span><StatementView value={entity} /><h4>Fields</h4>{entity.fields.map((s,n) => <StatementView key={n} value={s} />)}<h4>Relationships</h4>{entity.relationships.map((s,n) => <StatementView key={n} value={s} />)}</article>)}{content.database.unresolved.map((s,n) => <StatementView key={n} value={s} />)}</section>
      <section className="brain-section"><h3>Features</h3>{content.features.map(f => <article key={f.feature_id}><div className="entry-meta">{f.feature_id} / {f.state}</div><StatementView value={f} /><p className="context-reference">Requirements: {f.requirement_ids.join(', ')}</p></article>)}</section>
      <section className="brain-section"><h3>Design decisions</h3>{content.design_decisions.map(d => <article key={d.decision_id}><span className="entry-meta">{d.decision_id}</span><h4>{d.choice}</h4><p>{d.reason}</p><ProvenanceLabel value={d.provenance} />{d.supersedes_decision_id && <p>Supersedes {d.supersedes_decision_id}</p>}</article>)}</section>
      <section className="brain-section"><h3>Constraints and open questions</h3>{content.constraints.map((s,n) => <StatementView key={`c${n}`} value={s} />)}{content.open_questions.map((s,n) => <StatementView key={`q${n}`} value={s} />)}</section>
      <section className="brain-section"><h3>Revision history references</h3><p>These references belong to this immutable revision. Current canonical history appears below.</p>{Object.entries(content.history).map(([k,v]) => <p key={k} className="context-reference">{k.replaceAll('_',' ')}: {v.join(', ') || 'None'}</p>)}</section>
      <section className="brain-section"><h3>Canonical requests and outcomes</h3><p>Saved requests: {result.data!.context.requests.length} · Issue events: {result.data!.context.issue_events.length} · Saved versions: {result.data!.context.versions.length} · Simulated deployments: {result.data!.context.deployments.length}</p>{result.data!.context.requests.map(r => <RequestCard key={r.id} record={r} />)}{result.data!.context.issue_events.map(e => <p key={e.id}>{e.mode === 'real' ? 'Real execution' : e.mode === 'simulated' ? 'Simulation' : 'Saved action'} · #{e.sequence} · {e.message}</p>)}{result.data!.context.versions.map(v => <details key={v.id}><summary>{v.mode === 'real' ? 'Version' : 'Demo version'} {v.number} · Saved build summary</summary><p>{v.summary}</p></details>)}{result.data!.context.deployments.map(d => <p key={d.id}>Simulated deployment · {d.status} · Internal fixture only</p>)}</section>
    </>}
  </div>;
}
export function ActivityView() {
  const { id } = useWorkspace(); const [after, setAfter] = useState('0'); const result = useResource<Events>(`/projects/${id}/events?after_sequence=${after}`);
  return <div className="workspace-document"><DocumentHeading index="03" title="Activity" description="Saved actions from the canonical project event records, ordered by server sequence. Real execution and Simulation retain distinct provenance." /><ResourceState {...result} />{result.data?.items.length === 0 && <p>No activity in this view.</p>}<ol className="activity-list">{result.data?.items.map(e => <li key={e.id}><div className="activity-time"><time dateTime={e.occurred_at}>{time(e.occurred_at)}</time><span>#{e.sequence}</span></div><div><span className="meta">{e.mode === 'simulated' ? 'SIMULATION' : e.mode === 'real' ? 'REAL EXECUTION' : 'SAVED USER ACTION'} / {e.severity}{e.phase ? ` / ${e.phase}` : ''}</span><p>{e.message}</p><details><summary>Event references</summary><dl><dt>Type</dt><dd>{e.type}</dd><dt>Actor</dt><dd>{e.payload.actor_user_id ?? 'Simulation'}</dd><dt>Request</dt><dd>{e.request_id ?? 'None'}</dd><dt>Run</dt><dd>{e.run_id ?? 'None'}</dd><dt>UTC timestamp</dt><dd>{e.occurred_at}</dd></dl></details></div></li>)}</ol><div className="record-pagination">{after !== '0' && <button onClick={() => setAfter('0')}>First events</button>}{result.data?.next_cursor && <button className="button button-secondary" onClick={() => setAfter(result.data!.next_cursor!)}>Next events</button>}</div></div>;
}
export function VersionsView() { const { id, snapshot } = useWorkspace(); const [cursor, setCursor] = useState(''); const result = useResource<Versions>(`/projects/${id}/versions${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ''}`); return <div className="workspace-document"><DocumentHeading index="04" title="Versions" description="Persisted successful outputs with their execution mode. Inspecting history never changes the current Brain or performs a rollback." /><ReleasePanel historyOnly/><ResourceState {...result} />{result.data?.items.length === 0 && <div className="workspace-empty-surface"><h3>No completed versions.</h3><p>Your first completed build will appear here, with its saved preview and verification records.</p></div>}{result.data?.items.map(v => <article className="version-record" key={v.id}><span className="meta">{v.mode === 'real' ? 'REAL EXECUTION' : 'SIMULATION'} / VERSION {v.number} · {v.id === snapshot.project.current_version_id ? 'CURRENT' : 'HISTORICAL'}</span><h3>{v.mode === 'real' ? `Version ${v.number}` : v.summary}</h3><time dateTime={v.created_at}>{time(v.created_at)}</time><details className="version-lineage"><summary>Version lineage</summary>{v.mode === 'real' && <p>Build summary: {v.summary}</p>}<dl><dt>Run</dt><dd>{v.run_id}</dd><dt>Brain revision ID</dt><dd>{v.brain_revision_id}</dd><dt>Version ID</dt><dd>{v.id}</dd></dl></details><Link className="text-action" href={`/projects/${id}?version=${v.id}`}>{v.mode === 'real' ? 'Inspect version preview ↗' : 'Inspect demo preview ↗'}</Link><Link className="text-action" href={`/projects/${id}?panel=run&run=${v.run_id}`}>{v.mode === 'real' ? 'Inspect build attempt ↗' : 'Inspect simulation attempt ↗'}</Link></article>)}{cursor && <button onClick={() => setCursor('')}>Latest versions</button>}{result.data?.next_cursor && <button className="button button-secondary" onClick={() => setCursor(result.data!.next_cursor!)}>Older versions</button>}</div>; }
export function SettingsView() { const { snapshot, refresh } = useWorkspace(); return <div className="workspace-document"><DocumentHeading index="05" title="Project settings" description="Manage this saved project’s title and archive state." /><ProjectSettings project={snapshot.project} onSaved={() => void refresh()} /><section className="brain-section"><h3>Environment and capabilities</h3><p>Build and production availability depend on the configured runtime. Review saved verification, preview and release records in this workspace.</p></section></div>; }
